#!/usr/bin/env python3
"""The paper's tables and plots, generated from the leaderboard entries.

Numbers retyped into a manuscript stop tracking the runs behind them the moment either
moves, and a paper is written once while the measurements keep being taken. So the tables
and the plotted data are not written in `paper/anvil.tex`: they are emitted here from
`leaderboard/entries/`, the same records the leaderboard page renders, and
`tests/test_paper.py` fails if the emitted files no longer match.

    ./scripts/paper_data.py            # write paper/data/
    ./scripts/paper_data.py --check    # fail if what is on disk is stale

Two files per task set. A `.dat` in the space-separated form `pgfplots` reads directly,
and a `.tex` fragment holding the `tabular` rows, so the manuscript says
`\\input{data/t1_slurm_table.tex}` and cannot disagree with the figure beside it.

What is not generated is the retrieval series in `paper/data/retrieval.dat`: those runs
are ablations rather than leaderboard entries, they have no place in a ranking, and the
file carries its provenance in a header comment instead.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from leaderboard import LEVELS, _load_entries  # noqa: E402

OUT = ROOT / "paper" / "data"

# The order the paper ranks and plots in, worst to best, so the reader's eye runs the same
# way in the table and along the bars. Models named here keep that order; anything else is
# appended by ascending strict score. It is a preference and not a filter: an earlier
# version was a filter, and a model added to the leaderboard would have been dropped from
# every table and figure without a word.
PREFERRED = [
    "Qwen/Qwen2.5-Coder-1.5B-Instruct",
    "Qwen/Qwen3.5-9B",
    "ibm-granite/granite-4.1-3b",
    "google/gemma-4-12B-it",
    "Qwen/Qwen2.5-Coder-7B-Instruct",
]

SHORT = {
    "Qwen/Qwen2.5-Coder-1.5B-Instruct": "Qwen2.5-Coder 1.5B",
    "Qwen/Qwen2.5-Coder-7B-Instruct": "Qwen2.5-Coder 7B",
    "ibm-granite/granite-4.1-3b": "Granite 4.1 3B",
    "google/gemma-4-12B-it": "Gemma 4 12B",
    "Qwen/Qwen3.5-9B": "Qwen3.5 9B",
}


def short(model: str) -> str:
    """A readable label. Unknown models fall back to the part after the owner, which is
    what a Hugging Face id carries anyway, rather than to nothing."""
    return SHORT.get(model, model.split("/", 1)[-1])


def order(cells: dict[tuple[str, str], dict]) -> list[tuple[str, str]]:
    """Cells are keyed by (model, executor), so a task file graded twice keeps both.

    Keying by model alone silently dropped one: `tasks/t1_exec.jsonl` has a `bash` and an
    `sbatch` entry per model, the second overwrote the first, and the table published one
    arm without saying which. On that set the two arms are the result.
    """
    ranked = sorted(
        cells,
        key=lambda k: (
            PREFERRED.index(k[0]) if k[0] in PREFERRED else len(PREFERRED),
            cells[k]["scores"].get("strict_all_levels", {}).get("mean", 0.0),
            k[1],
        ),
    )
    return ranked


def _by_tasks() -> dict[str, dict[tuple[str, str], dict]]:
    out: dict[str, dict[tuple[str, str], dict]] = {}
    for entry in _load_entries():
        out.setdefault(entry["tasks_file"], {})[(entry["model"], entry["executor"])] = entry
    return out


def label(cells: dict, key: tuple[str, str]) -> str:
    """The executor is named only where a task file carries more than one, so the tables
    that have always had a single arm read exactly as before."""
    model, executor = key
    arms = {k[1] for k in cells}
    return short(model) + (f" ({executor})" if len(arms) > 1 else "")


def _dat(models: dict[str, dict]) -> str:
    """One row per level, one column per model: what `pgfplots` reads for grouped bars.

    The x axis is the index and not the level name. A symbolic coordinate carrying
    `resource_fit` would reach the tick label with its underscore intact and stop the
    build, so the manuscript owns the labels and this file owns the numbers.
    """
    present = order(models)
    head = "idx level " + " ".join(f"m{i}" for i, _ in enumerate(present))
    lines = [
        "# generated by scripts/paper_data.py from leaderboard/entries/, do not edit",
        "# columns: " + ", ".join(label(models, k) for k in present),
        head,
    ]
    for i, level in enumerate(LEVELS):
        values = [f"{models[m]['scores'][level]['mean']:.4f}" for m in present]
        lines.append(f"{i} {level} " + " ".join(values))
    return "\n".join(lines) + "\n"


def _table(models: dict[str, dict]) -> str:
    """The `tabular` body only: the manuscript owns the column specification and caption.

    The last row deliberately has no `\\\\`. Ending an `\\input` file with a row terminator
    inside an alignment makes TeX look ahead for the optional argument of `\\\\`, run off the
    end of the file, and read the following `\\bottomrule` while the row is still open,
    which it reports as a misplaced `\\noalign`. The manuscript closes the row instead.
    """
    # `safety` is 1.000 for every model on every task set. A column of identical values
    # costs width and carries nothing, so the table states it in the caption instead. The
    # figure keeps it, where a flat bar is informative rather than redundant.
    columns = [lv for lv in LEVELS if lv != "safety"]
    rows = []
    for key in order(models):
        entry = models[key]
        cells = [
            f"${entry['scores'][lv]['mean']:.3f} \\pm {entry['scores'][lv]['half_range']:.3f}$"
            for lv in columns
        ]
        rows.append(f"{label(models, key)} & " + " & ".join(cells))
    body = " \\\\\n".join(rows)
    return "% generated by scripts/paper_data.py, do not edit\n" + body + "\n"


def build() -> dict[str, str]:
    files: dict[str, str] = {}
    for tasks_file, models in _by_tasks().items():
        stem = Path(tasks_file).stem
        files[f"{stem}.dat"] = _dat(models)
        files[f"{stem}_table.tex"] = _table(models)
    return files


def main(argv: list[str]) -> int:
    files = build()
    if "--check" in argv:
        stale = [
            name for name, body in files.items()
            if not (OUT / name).exists() or (OUT / name).read_text(encoding="utf-8") != body
        ]
        if stale:
            print(f"stale, regenerate with ./scripts/paper_data.py: {', '.join(stale)}",
                  file=sys.stderr)
            return 1
        print("the paper's data files match the leaderboard entries")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    for name, body in files.items():
        (OUT / name).write_text(body, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {', '.join(sorted(files))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
