#!/usr/bin/env python3
"""The paper's tables and plots, generated from the leaderboard entries.

Numbers retyped into a manuscript stop tracking the runs behind them the moment either
moves, and a paper is written once while the measurements keep being taken. So the tables
and the plotted data are not written in `paper/anvil.tex`: they are emitted here from
`leaderboard/entries/`, the same records the leaderboard page renders, and
`tests/test_paper.py` fails if the emitted files no longer match.

    ./scripts/paper_data.py            # write paper/data/
    ./scripts/paper_data.py --check    # fail if what is on disk is stale

Two files per task set. A `.dat` in the space-separated form `pgfplots` reads directly,
and a `.tex` fragment holding the `tabular` rows, so the manuscript says
`\\input{data/t1_slurm_table.tex}` and cannot disagree with the figure beside it.

What is not generated is the retrieval series in `paper/data/retrieval.dat`: those runs
are ablations rather than leaderboard entries, they have no place in a ranking, and the
file carries its provenance in a header comment instead.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from leaderboard import LEVELS, _load_entries  # noqa: E402

OUT = ROOT / "paper" / "data"

# The order the paper ranks and plots in, worst to best, so the reader's eye runs the same
# way in the table and along the bars.
ORDER = [
    "Qwen/Qwen2.5-Coder-1.5B-Instruct",
    "ibm-granite/granite-4.1-3b",
    "Qwen/Qwen2.5-Coder-7B-Instruct",
]

SHORT = {
    "Qwen/Qwen2.5-Coder-1.5B-Instruct": "Qwen2.5-Coder 1.5B",
    "Qwen/Qwen2.5-Coder-7B-Instruct": "Qwen2.5-Coder 7B",
    "ibm-granite/granite-4.1-3b": "Granite 4.1 3B",
}


def _by_tasks() -> dict[str, dict[str, dict]]:
    out: dict[str, dict[str, dict]] = {}
    for entry in _load_entries():
        out.setdefault(entry["tasks_file"], {})[entry["model"]] = entry
    return out


def _dat(models: dict[str, dict]) -> str:
    """One row per level, one column per model: what `pgfplots` reads for grouped bars.

    The x axis is the index and not the level name. A symbolic coordinate carrying
    `resource_fit` would reach the tick label with its underscore intact and stop the
    build, so the manuscript owns the labels and this file owns the numbers.
    """
    present = [m for m in ORDER if m in models]
    head = "idx level " + " ".join(f"m{i}" for i, _ in enumerate(present))
    lines = [
        "# generated by scripts/paper_data.py from leaderboard/entries/, do not edit",
        "# columns: " + ", ".join(SHORT[m] for m in present),
        head,
    ]
    for i, level in enumerate(LEVELS):
        values = [f"{models[m]['scores'][level]['mean']:.4f}" for m in present]
        lines.append(f"{i} {level} " + " ".join(values))
    return "\n".join(lines) + "\n"


def _table(models: dict[str, dict]) -> str:
    """The `tabular` body only: the manuscript owns the column specification and caption."""
    lines = ["% generated by scripts/paper_data.py, do not edit"]
    for model in ORDER:
        entry = models.get(model)
        if entry is None:
            continue
        cells = [
            f"${entry['scores'][lv]['mean']:.3f} \\pm {entry['scores'][lv]['half_range']:.3f}$"
            for lv in LEVELS
        ]
        lines.append(f"{SHORT[model]} & " + " & ".join(cells) + r" \\")
    return "\n".join(lines) + "\n"


def build() -> dict[str, str]:
    files: dict[str, str] = {}
    for tasks_file, models in _by_tasks().items():
        stem = Path(tasks_file).stem
        files[f"{stem}.dat"] = _dat(models)
        files[f"{stem}_table.tex"] = _table(models)
    return files


def main(argv: list[str]) -> int:
    files = build()
    if "--check" in argv:
        stale = [
            name for name, body in files.items()
            if not (OUT / name).exists() or (OUT / name).read_text(encoding="utf-8") != body
        ]
        if stale:
            print(f"stale, regenerate with ./scripts/paper_data.py: {', '.join(stale)}",
                  file=sys.stderr)
            return 1
        print("the paper's data files match the leaderboard entries")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    for name, body in files.items():
        (OUT / name).write_text(body, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {', '.join(sorted(files))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
